name: CI Pipeline for SDK - Python

on:
  push:
    branches: ["main"]

jobs:
  test:
    needs: ["gen"]
    uses: openclimatefix/.github/.github/workflows/python-test.yml@working-directory
    with:
      workdir: sdk/python
      pytest_cov_dir: pvsite_datamodel

  publish:
    # needs: ["test"]
    uses: openclimatefix/.github/.github/workflows/python-release.yml@working-directory
    secrets:
      token: ${{ secrets.PYPI_API_TOKEN }}
    with:
      workdir: sdk/python
