name: Test SDK - Python

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install unittest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        run: unittest discover -s ~/sdk/pvsite-python -t ~/sdk/pvsite-python
